
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadorfc;

/** CUP generated class containing symbol constants. */
public class AnalizadorSintacticoSym {
  /* terminals */
  public static final int NUM = 11;
  public static final int OpDiv = 6;
  public static final int ParDer = 10;
  public static final int MENOSUNARIO = 15;
  public static final int OpSuma = 3;
  public static final int SEMIC = 2;
  public static final int OpResta = 4;
  public static final int CONST_PRED = 13;
  public static final int EOF = 0;
  public static final int VAR = 12;
  public static final int OpProd = 5;
  public static final int OpPotencia = 8;
  public static final int OpAsig = 7;
  public static final int error = 1;
  public static final int BLTIN = 14;
  public static final int ParIzq = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMIC",
  "OpSuma",
  "OpResta",
  "OpProd",
  "OpDiv",
  "OpAsig",
  "OpPotencia",
  "ParIzq",
  "ParDer",
  "NUM",
  "VAR",
  "CONST_PRED",
  "BLTIN",
  "MENOSUNARIO"
  };
}

