/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package analizadorfc;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;

/**
 *
 * @author roman
 */
public class formHoc3 extends javax.swing.JFrame {
    AnalizadorSintactico Sintac;
    /**
     * Creates new form formHoc3
     */
    public formHoc3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoAAnalizar = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaTokens = new javax.swing.JTextArea();
        btnAnalizLexico = new javax.swing.JButton();
        btnSintactico = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultSintactico = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Expresion a analizar");

        TextoAAnalizar.setColumns(20);
        TextoAAnalizar.setRows(5);
        jScrollPane1.setViewportView(TextoAAnalizar);

        txtAreaTokens.setColumns(20);
        txtAreaTokens.setRows(5);
        jScrollPane2.setViewportView(txtAreaTokens);

        btnAnalizLexico.setText("Analizar Lexicamente");
        btnAnalizLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizLexicoActionPerformed(evt);
            }
        });

        btnSintactico.setText("Sintactico");
        btnSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSintacticoActionPerformed(evt);
            }
        });

        txtResultSintactico.setColumns(20);
        txtResultSintactico.setRows(5);
        jScrollPane3.setViewportView(txtResultSintactico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSintactico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnalizLexico)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSintactico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnalizLexico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizLexicoActionPerformed
        // TODO add your handling code here:
        Symbol simb;
        String lexema = new String();
        String CadAux = new String();
        File ArchEntrada = new File("ArchEntrada.txt");
        PrintWriter escribir;
        txtAreaTokens.setText("");
        
        try {
            escribir = new PrintWriter(ArchEntrada);
            escribir.print(TextoAAnalizar.getText());
            escribir.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(formHoc3.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Reader lector;
            lector = new FileReader("ArchEntrada.txt");

            AnalizadorLexico AnalizLexico = new AnalizadorLexico(lector);

            do {
                simb = AnalizLexico.next_token();
                CadAux = Integer.toString(simb.sym);
                lexema = AnalizLexico.yytext();
                if (simb.sym == AnalizadorSintacticoSym.EOF)
                    CadAux = "Token: " + CadAux + " \t IdentTOKEN: FIN\n";
                else 
                    switch (simb.sym) {
                        case AnalizadorSintacticoSym.SEMIC:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: SEMIC\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.NUM:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: NUM\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.CONST_PRED:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: CONST_PRED\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.BLTIN:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: BLTIN\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpAsig:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: OpAsig\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpSuma:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: OpSuma\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpResta:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: OpResta\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpProd:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: OpProd\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpDiv:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: OpDiv\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.ParIzq:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: ParIzq\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.ParDer:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: ParDer\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.error:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: error\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.VAR:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: VAR\t Lexema: " + lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpPotencia:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: OpPotencia\t Lexema: " + lexema + "\n";
                            break;
                        default:
                            CadAux = "Token: " + CadAux + " \t IdentTOKEN: OTRO\t Lexema: " + AnalizLexico.yytext() + "\n";
                            break;
                    }
                txtAreaTokens.append(CadAux);
            } while (simb.sym != AnalizadorSintacticoSym.EOF);
        } catch (IOException ex) {
            txtAreaTokens.append("Entro al catch \n");
            Logger.getLogger(formHoc3.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtAreaTokens.repaint();
    }//GEN-LAST:event_btnAnalizLexicoActionPerformed

    private void btnSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSintacticoActionPerformed
        // TODO add your handling code here:
        String CadAux = new String();
        String CadInst = new String();
        String Name = new String();
        String Valor = new String();
        String ptrFunc = new String();
        Object os[] = new Object [5];

        AnalizadorLexico Lexic = null;

        try {
            Lexic = new AnalizadorLexico(new FileReader("ArchEntrada.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(formHoc3.class.getName()).log(Level.SEVERE, null, ex);
        }

        Sintac = new AnalizadorSintactico(Lexic);
        Sintac.frmInterfaz = this;

        try {
            Object result = Sintac.parse().value;
        } catch (Exception ex) {
            Logger.getLogger(formHoc3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSintacticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formHoc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formHoc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formHoc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formHoc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formHoc3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea TextoAAnalizar;
    private javax.swing.JButton btnAnalizLexico;
    private javax.swing.JButton btnSintactico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea txtAreaTokens;
    public javax.swing.JTextArea txtResultSintactico;
    // End of variables declaration//GEN-END:variables
}
